# Generated by Django 2.2.12 on 2020-04-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mongo',
            new_name='Convai',
        ),
        migrations.AlterModelTable(
            name='convai',
            table='convai',
        ),
    ]
