# Generated by Django 2.2.12 on 2020-04-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_auto_20200407_1343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='convai',
            table='convai.user-data',
        ),
    ]
